"use client";
import { useMemo, useState } from "react";
import { LearnNav } from "../LearnNav";

const layers=[
 {name:"API Edge",detail:"Auth, quotas, schema validation, idempotency, request IDs"},
 {name:"AI Gateway",detail:"Model routing, fallbacks, budgets, semantic cache"},
 {name:"Safety",detail:"Input moderation, PII redaction, prompt-injection defense"},
 {name:"Context Engine",detail:"Query rewrite, hybrid retrieval, reranking, citations"},
 {name:"Inference",detail:"Streaming, tool calls, structured output, cancellation"},
 {name:"Evaluation",detail:"Traces, quality scores, latency, cost, drift monitoring"},
];
const patterns=[
 ["AI Gateway","Hide providers behind one contract. Route by task, cost, latency, region, and availability."],
 ["RAG Pipeline","Retrieve trusted context, rerank it, assemble a bounded prompt, and return grounded citations."],
 ["Tool-Using Agent","Let the model choose allowlisted tools while the application owns state, validation, and side effects."],
 ["Semantic Cache","Reuse responses for equivalent requests when freshness, identity, and safety constraints allow it."],
 ["Fallback Chain","Degrade from quality model to fast model, deterministic search, or cached response under failure."],
 ["Async Job","Move long generations to a durable queue with status polling, callbacks, cancellation, and retries."],
];

export default function GenAiPage(){
 const [active,setActive]=useState(1);const [quality,setQuality]=useState(64);const [rag,setRag]=useState(true);const [streaming,setStreaming]=useState(true);const [running,setRunning]=useState(false);const [stage,setStage]=useState(0);const [pattern,setPattern]=useState(0);
 const metrics=useMemo(()=>({latency:Math.round(240+quality*8+(rag?90:0)),cost:(.0012+quality*.00008+(rag?.0004:0)).toFixed(4),tokens:Math.round(220+quality*13+(rag?900:0)),quality:Math.min(98,55+Math.round(quality*.36)+(rag?12:0))}),[quality,rag]);
 function run(){setRunning(true);setStage(1);[2,3,4,5,6].forEach((n,i)=>setTimeout(()=>setStage(n),(i+1)*480));setTimeout(()=>setRunning(false),3400)}
 return <main className="course-page ai-page"><LearnNav/><header className="course-hero shell ai-hero"><span className="course-index">GENAI / 05</span><h1>Design AI backends.<br/><em>Beyond the model call.</em></h1><p>Build reliable GenAI systems with RAG, streaming, tool execution, provider routing, safety, evaluation, observability, and cost control.</p><div className="ai-status"><span/><b>AI SYSTEM ONLINE</b><small>6 layers · streaming enabled</small></div></header>
 <section className="ai-pipeline shell"><div className="section-head"><div><span className="kicker">LIVE INFERENCE PIPELINE</span><h2>One request.<br/><em>Six guarded stages.</em></h2></div><p>Click a layer to inspect its production responsibility, then run the complete animated request.</p></div><div className="ai-stage"><aside>{layers.map((x,i)=><button className={active===i?"active":""} key={x.name} onClick={()=>setActive(i)}><span>0{i+1}</span><div><b>{x.name}</b><small>{x.detail}</small></div><i>{stage>i?"✓":"→"}</i></button>)}</aside><div className="ai-flow"><div className="ai-grid"/><div className="ai-request">PROMPT<span>&quot;Design a global feed&quot;</span></div><div className="ai-rail">{layers.map((x,i)=><div key={x.name} className={stage>i?"ai-node passed":"ai-node"}><i>{i+1}</i><b>{x.name}</b>{i<5&&<span/>}</div>)}</div><div className="ai-detail" key={active}><small>ACTIVE LAYER</small><b>{layers[active].name}</b><p>{layers[active].detail}</p></div><button onClick={run} disabled={running}>{running?`Processing stage ${stage}/6…`:"Run inference flow →"}</button></div></div></section>
 <section className="ai-console-section"><div className="shell"><div className="section-head light"><div><span className="kicker">GENAI API PLAYGROUND</span><h2>Balance quality,<br/><em>latency, and cost.</em></h2></div><p>Adjust routing decisions and watch the prediction graph and request contract update immediately.</p></div><div className="ai-console"><div className="ai-controls"><label><span>Model quality <b>{quality}%</b></span><input type="range" min="10" max="100" value={quality} onChange={e=>setQuality(Number(e.target.value))}/></label><button className={rag?"on":""} onClick={()=>setRag(!rag)}><span><b>Retrieval augmented</b><small>Hybrid search + reranking</small></span><i><u/></i></button><button className={streaming?"on":""} onClick={()=>setStreaming(!streaming)}><span><b>Token streaming</b><small>Improve time to first token</small></span><i><u/></i></button><div className="ai-metrics"><div><small>P95 LATENCY</small><b>{metrics.latency}ms</b></div><div><small>COST / REQUEST</small><b>${metrics.cost}</b></div><div><small>QUALITY SCORE</small><b>{metrics.quality}</b></div></div></div><div className="ai-code"><div><span>POST /api/v1/ai/inference</span><b>{streaming?"text/event-stream":"application/json"}</b></div><pre>{`{\n  "prompt": "Explain consistent hashing",\n  "model": "${quality>70?"quality":"fast"}",\n  "useRag": ${rag},\n  "stream": ${streaming},\n  "maxTokens": ${metrics.tokens}\n}`}</pre><div className="token-stream"><span>RESPONSE</span><p>{streaming?"System design is the process of defining architecture":"{ \"answer\": \"System design is…\" }"}<i/></p></div></div><div className="ai-graph"><span>QUALITY / COST CURVE</span><div className="ai-bars">{[22,31,43,58,74,91].map((h,i)=><i key={h} style={{height:`${Math.min(96,h+quality/9)}%`,animationDelay:`${i*70}ms`}}><small>{i+1}</small></i>)}</div><div className="ai-budget">BUDGET LIMIT</div></div></div></div></section>
 <section className="ai-patterns shell"><div className="section-head"><div><span className="kicker">BACKEND PATTERN CATALOG</span><h2>Six patterns for<br/><em>production AI.</em></h2></div><p>The model is a dependency. Your backend must own reliability, data boundaries, orchestration, and measurable quality.</p></div><div className="ai-pattern-layout"><div>{patterns.map((x,i)=><button className={pattern===i?"active":""} key={x[0]} onClick={()=>setPattern(i)}><span>0{i+1}</span><b>{x[0]}</b><i>→</i></button>)}</div><article key={pattern}><small>GENAI BACKEND PATTERN</small><h3>{patterns[pattern][0]}</h3><p>{patterns[pattern][1]}</p><div className="mini-ai-diagram"><div>CLIENT</div><i>→</i><div className="hot">{patterns[pattern][0].toUpperCase()}</div><i>→</i><div>PROVIDER</div><span className="mini-packet"/></div><ul><li>Explicit timeout and cancellation</li><li>Trace every decision and model call</li><li>Budget tokens and concurrency</li><li>Test quality with versioned eval sets</li></ul></article></div></section>
 <section className="ai-checklist shell"><h2>Production readiness</h2><div>{["Threat model","PII boundary","Prompt versioning","Eval dataset","Model fallback","Vector index","Citation checks","Tool allowlist","Rate limits","Token budget","Semantic cache","Trace sampling","Cost alerts","Human escalation","Rollback plan"].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b><i>✓</i></article>)}</div></section></main>
}
