"use client";
import { useMemo, useState } from "react";
import { LearnNav } from "../LearnNav";

const methods: Record<string,{path:string,purpose:string,body:string,response:string,status:string}>={
 GET:{path:"/api/v1/users?limit=20&cursor=abc",purpose:"Read a collection safely with filtering and cursor pagination.",body:"No request body",response:'{"data":[{"id":"usr_01","name":"Ada"}],"nextCursor":"def"}',status:"200 OK"},
 POST:{path:"/api/v1/users",purpose:"Create a resource; validate input and support an idempotency key.",body:'{"name":"Ada","email":"ada@example.com"}',response:'{"id":"usr_01","name":"Ada","version":1}',status:"201 CREATED"},
 PUT:{path:"/api/v1/users/usr_01",purpose:"Replace the full resource representation at a stable URI.",body:'{"name":"Ada Lovelace","email":"ada@example.com"}',response:'{"id":"usr_01","name":"Ada Lovelace","version":2}',status:"200 OK"},
 PATCH:{path:"/api/v1/users/usr_01",purpose:"Apply a partial update with optimistic concurrency.",body:'{"name":"Ada Byron"}',response:'{"id":"usr_01","name":"Ada Byron","version":3}',status:"200 OK"},
 DELETE:{path:"/api/v1/users/usr_01",purpose:"Delete idempotently or mark for asynchronous deletion.",body:"No request body",response:"No response body",status:"204 NO CONTENT"},
 HEAD:{path:"/api/v1/users/usr_01",purpose:"Read headers and cache metadata without transferring a body.",body:"No request body",response:"ETag: W/\"usr_01-v3\"",status:"200 OK"},
 OPTIONS:{path:"/api/v1/users",purpose:"Discover allowed methods and CORS capabilities.",body:"No request body",response:"Allow: GET, POST, OPTIONS",status:"204 NO CONTENT"},
};
const apiStyles=["REST","GraphQL","gRPC","WebSocket","SSE","Webhook","AsyncAPI","tRPC"];
export default function ApiPage(){const [method,setMethod]=useState("GET");const [running,setRunning]=useState(false);const [history,setHistory]=useState<{m:string;ms:number;status:string}[]>([]);const [traffic,setTraffic]=useState(35);const data=methods[method];const latency=useMemo(()=>Math.round(18+traffic*1.7+Math.pow(traffic/100,3)*240),[traffic]);function send(){setRunning(true);setTimeout(()=>{setRunning(false);setHistory(h=>[{m:method,ms:latency,status:data.status},...h].slice(0,6))},620)}
return <main className="course-page"><LearnNav/><header className="course-hero shell"><span className="course-index">API / 03</span><h1>Design. Test.<br/><em>Optimize every API.</em></h1><p>All REST methods plus modern API styles, real request semantics, validation, versioning, authentication, errors, caching, observability, and performance.</p><div className="api-style-strip">{apiStyles.map(x=><span key={x}>{x}</span>)}</div></header><section className="api-workbench shell"><div className="method-tabs">{Object.keys(methods).map(x=><button key={x} className={method===x?"active":""} onClick={()=>setMethod(x)}>{x}</button>)}</div><div className="request-studio"><article><span>01 / REQUEST CONTRACT</span><h2>{method}</h2><p>{data.purpose}</p><label>ENDPOINT<code>{data.path}</code></label><label>BODY<pre>{data.body}</pre></label><button onClick={send} disabled={running}>{running?"Sending through stack…":"Send live simulation →"}</button></article><article className={running?"api-response running":"api-response"}><span>02 / RESPONSE</span><b>{data.status}</b><pre>{running?"Gateway → Auth → Validation → Service → Database":data.response}</pre><div className="waterfall">{["DNS","TLS","EDGE","APP","DB"].map((x,i)=><i key={x} style={{width:`${14+i*11}%`,animationDelay:`${i*90}ms`}}><small>{x}</small></i>)}</div><strong>{latency}ms p95</strong></article><aside><span>REQUEST HISTORY</span>{history.length?history.map((h,i)=><div key={i}><b>{h.m}</b><code>{h.status}</code><small>{h.ms}ms</small></div>):<p>Run a request to populate traces.</p>}</aside></div><div className="perf-lab"><div><small>LIVE PERFORMANCE LAB</small><h3>Traffic vs. latency</h3><label>LOAD <b>{traffic}k req/s</b><input type="range" min="1" max="100" value={traffic} onChange={e=>setTraffic(Number(e.target.value))}/></label><ul><li><b>Cache:</b> CDN + Redis cache-aside</li><li><b>Database:</b> composite index + read replica</li><li><b>Protection:</b> token bucket + backpressure</li></ul></div><div className="live-graph"><div className="graph-threshold">SLO 200ms</div><div className="graph-area" style={{height:`${Math.min(92,latency/3)}%`}}/><i style={{bottom:`${Math.min(88,latency/3)}%`}}/><span>{latency}ms</span><footer><small>0</small><small>25k</small><small>50k</small><small>75k</small><small>100k RPS</small></footer></div></div></section><section className="api-checklist shell"><h2>Production API checklist</h2><div>{["Schema validation","Authentication","Authorization","Idempotency","Rate limiting","Pagination","Versioning","Caching","Timeouts","Retries + jitter","Circuit breakers","Structured errors","OpenAPI / AsyncAPI","Metrics + traces","Load testing","Backward compatibility"].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b><i>✓</i></article>)}</div></section></main>}
